shell /usr/bin/zsh

background          #333333
foreground          #ffffff
cursor              #00ff00
selection_background #b5d5ff
color0              #4d4d4d
color8              #545454
color1              #ff2b2b
color9              #ff5555
color2              #98fb98
color10             #55ff55
color3              #f0e68c
color11             #ffff55
color4              #cd853f
color12             #87ceff
color5              #ffdead
color13             #ff55ff
color6              #ffa0a0
color14             #ffd700
color7              #f5deb3
color15             #ffffff
selection_foreground #333333


include ./kitty-themes/themes/ayu.conf
#include ./kitty-themes/themes/Dracula.conf

font_family      FiraCode Nerd Font
font_size        12.0
font_features    FiraCode-Regular +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +cv31

# Padding within the window (espaçamento interno)
window_padding_width 5

window_margin_width 3

background_opacity 0.8
background_image_layout scaled

tab_bar_style powerline

# Border width for tiled windows
window_border_width 1pt

map ctrl+enter new_window_with_cwd
map ctrl+l clear
map f9 close_other_windows_in_tab


#enabled_layouts tall:bias=50;full_size=1;mirrored=false

#┌──────────────┬───────────────┐
#│              │               │
#│              │               │
#│              │               │
#│              ├───────────────┤
#│              │               │
#│              │               │
#│              │               │
#│              ├───────────────┤
#│              │               │
#│              │               │
#│              │               │
#└──────────────┴───────────────┘

enabled_layouts fat:bias=50;full_size=1;mirrored=false

┌──────────────────────────────┐
│                              │
│                              │
│                              │
│                              │
├─────────┬──────────┬─────────┤
│         │          │         │
│         │          │         │
│         │          │         │
│         │          │         │
│         │          │         │
└─────────┴──────────┴─────────┘
